### ISSUE TITLE
DynamoDB: table name can't be surround by single quotation marks

### ISSUE THREAD

**Issue by khanh-alice** [getmoto/py-partiql-parser#25]
Unsure if it's used to work or intended, but I notice that `moto` allows DynamoDB's table name to be surround by single quotation marks. This is not the case on an real DynamoDB.

Given `main.py`

```python
import boto3


def execute_statement():
    client = boto3.client("dynamodb", region_name="us-east-1")

    table_name = "testtable"
    response = client.execute_statement(Statement=f"select pk from '{table_name}'")

    items = response.get("Items")
    print(items)


if __name__ == "__main__":
    execute_statement()
```

and `main_test.py`

```python
import boto3
from moto import mock_aws


@mock_aws
def test_main():
    client = boto3.client("dynamodb", region_name="us-east-1")
    table_name = "testtable"

    client.create_table(
        TableName=table_name,
        KeySchema=[
            {"AttributeName": "pk", "KeyType": "HASH"},
        ],
        AttributeDefinitions=[
            {"AttributeName": "pk", "AttributeType": "S"},
        ],
        BillingMode="PAY_PER_REQUEST",
    )
    client.put_item(
        TableName=table_name,
        Item={
            "pk": {"S": "1"},
        },
    )

    from main import execute_statement
    execute_statement()
```

Running `main.py` return this error

```console
Traceback (most recent call last):
  File "/Users/khanh.le/Git/mototest/main.py", line 15, in <module>
    execute_statement()
  File "/Users/khanh.le/Git/mototest/main.py", line 8, in execute_statement
    response = client.execute_statement(Statement=f"select pk from '{table_name}'")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khanh.le/Git/mototest/.venv/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khanh.le/Git/mototest/.venv/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the ExecuteStatement operation: Unexpected from source
```

But running `moto_test.py` returns a successful test.

A quick check on PartiQL Editor on AWS console also shows some kind of errors when I try surround the table name with single quotation mark.

`SELECT`
<img width="998" alt="image" src="https://github.com/user-attachments/assets/10ac6a10-4c45-4260-a387-c812abc8fc9e">

`UPDATE`
<img width="998" alt="image" src="https://github.com/user-attachments/assets/7f447d8f-4607-4f34-ab71-05b18d384107">

`DELETE`
<img width="998" alt="image" src="https://github.com/user-attachments/assets/4c7fab7e-d446-4e56-b639-7787b47c0841">

`INSERT`
<img width="998" alt="image" src="https://github.com/user-attachments/assets/d3468946-3f1e-4d42-aeed-1b28ce7a62b5">

```txt
boto3==1.35.29
botocore==1.35.29
moto==5.0.16
py-partiql-parser==0.5.6
```

**Comment by bblommers** [comment]
I looked into this at some point, and I remember being.. bewildered by AWS' choices. 

Not sure about the details - was it that AWS allows both no quotes or double quotes, but not single quotes? Either that, or there were inconsistencies in what types of quotes they accept/require for other parts of the query, like attributes.

It is confusing either way, and it would be nice if we could at least match the behaviour, so I'll mark it as an enhancement to add this validation.
